import assert from 'node:assert/strict';
import { launchOptions } from './browser-runtime.mjs';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch(launchOptions());
try {
  const page = await browser.newPage({ viewport: { width: 1100, height: 820 }, colorScheme: 'light' });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => { if (window === window.top) localStorage.setItem('codex-webui-locale', 'zh-CN'); });
  await page.goto(process.env.CODEX_WEBUI_TEST_URL || 'http://127.0.0.1:8899', { waitUntil: 'networkidle' });
  await page.waitForFunction(() => globalThis.__codexWebuiDebug?.state?.config?.home);
  await page.click('#newTask');
  assert.equal(await page.locator('#toggleSidebar').getAttribute('aria-expanded'), 'true', 'desktop new task keeps sidebar open');
  const project = await page.evaluate(() => {
    const api = globalThis.__codexWebuiDebug;
    api.startNewTask(); api.setProjectless();
    return api.state.threads.find(thread => !thread.projectless && thread.cwd && thread.cwd !== api.state.config.home)?.cwd;
  });
  assert.ok(project, 'live project list must contain a project');
  const draft = '保留正在输入的草稿';
  await page.locator('#prompt').fill(draft);
  assert.ok(await page.locator('#composerProjectBar').isVisible());
  assert.equal(await page.locator('#composerProjectLabel').textContent(), '选择项目');
  await page.click('#composerProjectButton');
  await page.locator('#composerProjectSearch').fill(project);
  const choice = page.locator('#composerProjectChoices button').filter({ hasText: project.split('/').at(-1) }).first();
  await choice.click();
  assert.equal(await page.locator('#prompt').inputValue(), draft);
  assert.equal(await page.evaluate(() => globalThis.__codexWebuiDebug.state.workspaceContext.cwd), project);
  assert.ok(await page.locator('#composerProjectRemove').isVisible());
  const bar = await page.locator('#composerProjectBar').boundingBox(), composer = await page.locator('#composer').boundingBox();
  assert.ok(bar.y < composer.y, 'project strip sits above the prompt');
  await page.locator('#composerProjectRemove').hover();
  assert.ok(await page.locator('.project-remove-icon').isVisible());
  await page.screenshot({ path: '/tmp/codex-project-selected-20260921.png' });
  await page.click('#composerProjectRemove');
  assert.equal(await page.locator('#prompt').inputValue(), draft);
  assert.equal(await page.evaluate(() => globalThis.__codexWebuiDebug.state.projectless), true);
  assert.equal(await page.locator('#composerProjectLabel').textContent(), '选择项目');
  assert.equal(await page.locator('#threadPath').textContent(), '');
  await page.click('#composerProjectButton');
  await page.locator('#composerProjectSearch').fill('no-matching-project-9876');
  assert.equal(await page.locator('#composerProjectChoices button').count(), 0);
  await page.locator('#composerProjectSearch').press('Escape');
  assert.ok(await page.locator('#composerProjectMenu').isHidden());
  assert.equal(await page.locator('#composerProjectButton').getAttribute('aria-expanded'), 'false');
  await page.click('#composerProjectButton');
  await Promise.all([page.waitForResponse(response => response.url().includes('/api/folders?')), page.click('#composerProjectBrowse')]);
  await page.waitForSelector('#folderDialog[open]');
  await page.locator('#folderPathInput').fill(project);
  await page.click('#folderGo');
  await page.waitForFunction(p => document.querySelector('#folderSelection').textContent === p, project, { timeout: 5000 }).catch(async error => { console.log({ project, selection:await page.locator('#folderSelection').textContent(), list:await page.locator('#folderList').textContent() }); throw error; });
  await page.click('#folderConfirm');
  assert.equal(await page.locator('#prompt').inputValue(), draft, 'folder selection preserves draft too');
  await page.click('#composerProjectRemove');
  await page.locator('#prompt').fill('@file');
  await page.waitForSelector('#composerAutocomplete [data-autocomplete-id="choose-project"]');
  await page.click('#composerAutocomplete [data-autocomplete-id="choose-project"]');
  await page.waitForSelector('#folderDialog[open]');
  await page.click('#folderDialog .folder-cancel');
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForFunction(() => globalThis.__codexWebuiDebug?.state?.projectless);
  assert.ok(await page.locator('#composerProjectBar').isVisible());
  assert.equal(await page.locator('#composerProjectLabel').textContent(), '选择项目');
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, colorScheme: 'light' });
  mobile.on('pageerror', error => errors.push(error.message));
  await mobile.addInitScript(() => { if (window === window.top) { localStorage.setItem('codex-webui-locale', 'zh-CN'); localStorage.setItem('codex-webui-project', '~'); } });
  await mobile.goto(process.env.CODEX_WEBUI_TEST_URL || 'http://127.0.0.1:8899', { waitUntil: 'networkidle' });
  await mobile.waitForFunction(() => globalThis.__codexWebuiDebug?.state?.projectless);
  await mobile.click('#toggleSidebar');
  assert.equal(await mobile.locator('#toggleSidebar').getAttribute('aria-expanded'), 'true');
  await mobile.click('#newTask');
  assert.equal(await mobile.locator('#toggleSidebar').getAttribute('aria-expanded'), 'false', 'mobile new task closes sidebar');
  assert.equal(await mobile.locator('#sidebar').evaluate(el => el.classList.contains('mobile-open')), false);
  await mobile.click('#composerProjectButton');
  const menu = await mobile.locator('#composerProjectMenu').boundingBox();
  assert.ok(menu.x >= 0 && menu.x + menu.width <= 390 && menu.y >= 0, 'mobile picker stays on screen');
  await mobile.screenshot({ path: '/tmp/codex-project-picker-mobile-20260921.png' });
  await page.evaluate(p => {
    const api = globalThis.__codexWebuiDebug;
    api.state.active = { id: 'existing', cwd: p, cachePreview: true }; api.renderHeader();
  }, project);
  assert.ok(await page.locator('#composerProjectBar').isHidden(), 'existing cached conversation has no project switcher');
  assert.deepEqual(errors, []);
  console.log('PASS: project strip, remove, search/select, draft preservation, folder picker, mentions, reload, mobile, existing conversation');
} finally { await browser.close(); }
